[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
<<<<<<< HEAD
tauri = { version = "2.2.3", features = [] }
=======
tauri = { version = "2.2.1", features = [] }
>>>>>>> b1ad9550682477a43598ebdc54534222ebb8d157
tauri-plugin-log = "2.0.0-rc"
